### PR TITLE
Fix NPE race in NettyResponseFuture.cancel (#2042)

### LINKED ISSUE #2042: NPE in at org.asynchttpclient.netty.channel.Channels.setAttribute(Channels.java:36)
java.lang.NullPointerException
	at org.asynchttpclient.netty.channel.Channels.setAttribute(Channels.java:36)
	at org.asynchttpclient.netty.channel.Channels.setDiscard(Channels.java:40)
	at org.asynchttpclient.netty.NettyResponseFuture.cancel(NettyResponseFuture.java:183)

### PR DESCRIPTION
**Pull request by pratt4**
Fixes #2042 

This is a typical TOCTOU (time-of-check/time-of-use) race https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use. 
The NPE was occurring because the channel field could be set to null by another thread between the check and its use:

if (channel != null) {                 // time-of-check
    Channels.setDiscard(channel);      //  time-of-use
    Channels.silentlyCloseChannel(channel);
}

By copying channel into a local variable in one atomic read, we ensure that—even if another thread changes the field—the local reference remains valid.

P.S. It is hard to write a deterministic test that fails consistently, so this PR only includes the code fix.

### CODE REVIEW

**Comment by pratt4** [comment]
HI @hyperxpro ...
can you please review this pr whenever you get time?

File: client/src/main/java/org/asynchttpclient/netty/NettyResponseFuture.java [hunk 1]
```diff
@@ -187,10 +187,10 @@ public boolean cancel(boolean force) {
             return false;
         }
 
-        // cancel could happen before channel was attached
-        if (channel != null) {
-            Channels.setDiscard(channel);
-            Channels.silentlyCloseChannel(channel);
+        Channel ch = channel; //atomic read, so that it won't end up in TOCTOU
```
Comment (hyperxpro) [inline client/src/main/java/org/asynchttpclient/netty/NettyResponseFuture.java:190]: final

Comment (pratt4) [reply client/src/main/java/org/asynchttpclient/netty/NettyResponseFuture.java]: Thank you for the review ...
updated the PR

**Review by hyperxpro — APPROVED** [review]
